version: '3.6'
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: develop-nginx
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./nginx.develop.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
    depends_on:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  app:
    build:
      context: .
      args:
        - COMPOSER_FLAGS=--prefer-dist --optimize-autoloader
    command: /usr/local/sbin/php-fpm
    container_name: develop-app
    restart: always
    ports:
      - 9001:9001
    environment:
      - OPCACHE_SAVE_COMMENTS=1
      - OPCACHE_VALIDATE_TIMESTAMPS=1
      - OPCACHE_REVALIDATE_FREQ=0
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - redis

  schedule:
    image: ibrunotome/php:7.4
    container_name: develop-schedule
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        chmod +x schedule.sh
        /var/www/schedule.sh
    environment:
      - OPCACHE_SAVE_COMMENTS=0
      - OPCACHE_VALIDATE_TIMESTAMPS=0
      - OPCACHE_REVALIDATE_FREQ=0
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis

  queue:
    image: ibrunotome/php:7.4
    container_name: develop-queue
    restart: always
    command: php artisan horizon
    environment:
      - OPCACHE_SAVE_COMMENTS=0
      - OPCACHE_VALIDATE_TIMESTAMPS=0
      - OPCACHE_REVALIDATE_FREQ=0
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis

  redis:
    image: redis:5.0.5-alpine
    container_name: develop-redis
    restart: always
    ports:
      - 6378:6378
    volumes:
      - redis-data:/data

volumes:
  redis-data:
